(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> define_table argument is not a Field or Table: []"
p3
sS'layer'
p4
S'C:\\Users\\Gabriel\\Documents\\Backend\\RAFA\\web2py\\applications\\RAFA\\models\\db.py'
p5
sS'code'
p6
S'<code object <module> at 092D64E8, file "C:\\Users\\Gabriel\\Documents\\Backend\\RAFA\\web2py\\applications\\RAFA\\models\\db.py", line 8>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\Gabriel\\Documents\\Backend\\RAFA\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\Users\\Gabriel\\Documents\\Backend\\RAFA\\web2py\\applications\\RAFA\\models\\db.py", line 163, in <module>\n    db.executesql(\'CREATE INDEX IF NOT EXISTS id_placa ON carros (placa);\')\n  File "C:\\Users\\Gabriel\\Documents\\Backend\\RAFA\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 587, in define_table\n    table = self.lazy_define_table(tablename, *fields, **args)\n  File "C:\\Users\\Gabriel\\Documents\\Backend\\RAFA\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 599, in lazy_define_table\n    table = table_class(self, tablename, *fields, **args)\n  File "C:\\Users\\Gabriel\\Documents\\Backend\\RAFA\\web2py\\gluon\\packages\\dal\\pydal\\objects.py", line 306, in __init__\n    field\nSyntaxError: define_table argument is not a Field or Table: []\n'
p11
s.